### ISSUE TITLE
Exclude vs Masked

### ISSUE THREAD

**Issue by mrvollger** [KiddLab/fastCN#1]
Hello,

I am working on getting FASTCN working on the T2T assembly and I am getting different GC control results depending on whether I include bases in `mask` vs `exclude`.  I thought that these would be treated the same but the code sets the GC to -INFINITY for masked regions and -1*CN for the exclude regions.
https://github.com/KiddLab/fastCN/blob/master/GC_control_gen.cc#L207-L210
https://github.com/KiddLab/fastCN/blob/master/GC_control_gen.cc#L221-L223
I guess I was hoping to have the exclude file treated just like the mask for the purpose of GC correction. Is this not the case?

Best,
Mitchell

**Comment by mrvollger** [comment]
Hello, 

Looking at the code a bit more and I am thinking that the -1 vs -INFINITY is not my issue. 

I think my issue may be the `Use_strict` filter applied to the exclude regions but not the masked regions.
https://github.com/KiddLab/fastCN/blob/5d6c677e17ba0927e5869f41be99f11512aba8d0/GC_control_gen.cc#L115-L129
Changing `Use_strict=1` to `Use_strict=0` gives me the control regions I was hoping for; however, I am not sure how large of an impact this might have on the results.

Could you give me any insight on whether its okay to change this flag or not?

Thanks in advance!
Mitchell

**Comment by jmkidd** [comment]
I'm not sure I understand your question.  Exclude and Mask regions are two different things.  

Exclude are regions that are potentially CNV/duplicated and therefore should not be used to build the GC correction profile.  However, GC correction is still applied to these regions and depth/copy-number is calculated for them.  An example of this would be a segmental duplication.  You want the estimated copy-number for the segdup, but do not want to use it to learn the GC correction curve.

Mask regions are places on the masked genome sequence that should not be considered.  This includes gaps, repeats masked to N, and the flanking "shadow" regions that are not masked to N.  These positions are totally ignored.  

In practice I'd guess that the GC curve is dominated by diploid sequence, since in most cases most of the genome is expected to be non-CNV. But they are conceptually distinct.

**Comment by mrvollger** [comment]
Sorry, our reasoning here is a little complex. But the basic idea is that there are of lot of sequences in T2T-CHM13 that we want to make CN calls for that are filtered out by dust masking and the mrsfast overrepresented 50mers masking. Our idea to remedy this was to move the Dust and mrsfast from the mask file to the exclude file, since while we want to CN genotype these regions we certainly do not want them to be used for making the GC correction curve. However, this ends up removing almost all windows from GC correction because most windows will fail the checks in the `Use_strict` statement.  

So I guess what I am asking is would it be reasonable for me to set `Use_strict=0` so that I can move the Dust and 50mer masking files into the exclude file? And then to approximate the `Use_strict=1` for the known SDs I could add a 400 bp slop to the input SD bed file?

**Comment by jmkidd** [comment]
The mask file should be regions that are masked out to N plus slop for the shadow effect.  If you are making calls in 
 regions, then they should not be masked to N and should not be part of the masked file.  But I understand that you do not want to use them for GC correction so adding them to the exclude bed seems reasonable.  If this results in not enough clean sequence (not near excluded regions) for GC normalization then you can try turning off the Use_strict option as you mention and expand some of the exclude intervals. In addition to expanding CNV regions by 400 I would consider expanding the Dust/50mer regions by 32 bp. Not sure how much of the genome that effects.   

We have not extensively tested this, which is why you have to edit the code rather than passing as a cmd line argument to set the option.  What does the GC correction curve .png file look like?  If that seems reasonable (mostly smooth with jaggedness at the low/high GC extremes, with a reasonable looking correction curve without big jumps)  then it is probably ok.  With newer Illumina data the GC step usually does not have a huge effect anyway.

**Comment by mrvollger** [comment]
Great, I will update once I have a few samples all the way through the pipeline! I really appreciate the responses.

**Comment by mrvollger** [comment]
I think these are reasonable GC curves, but I am still waiting for a few more to go through before I look too closely. 

![image](https://user-images.githubusercontent.com/6935283/133871004-b727c499-6e50-4af5-a59b-223622b47bbf.png)
![image](https://user-images.githubusercontent.com/6935283/133871031-6ae7bce1-2de5-4358-9ef0-f56b1ee35e6d.png)

**Comment by mrvollger** [comment]
Overall I think I have pretty good GC correction. I have attached the png for 20 runs in case you are interested and if you notice anything off please let me know. Thanks again!
[fastcnpng.zip](https://github.com/KiddLab/fastCN/files/7192975/fastcnpng.zip)
